<!-- $Id: faq.inc,v 1.14.4.4 2003/12/15 16:00:10 seth Exp $ -->
<span class="subtitle">Frequently Asked Questions</span>
<br />

<p><a name="welcome"></a>Welcome to planworld! We hope to address most of your major
concerns with this brief FAQ.  If after reading this help section,
your questions or concerns persist, don't hesitate to
<a href="mailto:<?php echo PW_EMAIL; ?>">email us</a>.</p>

<p><a name="plans"></a><i><u>What is a plan? Why should I have
one?</u></i><br /> Plans serve as a sort of online bulletin board for
students, alumni, and faculty of Amherst College.  Most users use
plans as a place for quotes, life updates, or world domination
strategies.  Feel free to post whatever you like on your plan, just
remember that anyone can view it.  Read the <a href="?id=about"
title="About">about</a> page for more information about plans and
their history.</p>

<p><a name="offcampus"></a><i><u>Can I use planworld off
campus?</u></i><br /> Planworld can be accessed from any computer that
has an internet connection and a web browser; whether you're in
Amherst, at home, or studying abroad.</p>

<p><a name="nonamherst"></a><i><u>Can non-Amherst persons access
planworld?</u></i><br />Amherst planworld is only accessible to
users with active NT or alumni accounts.  However, if you have friends who would like to get involved, they can register on <a href="http://www.planworld.net/">planworld.net</a>.  Their plan will be available by fingering <strong><i>username</i>@planworld.net</strong> and they can read yours by fingering <strong><i>username</i>@amherst.edu</strong> as long as you have configured yours to be <i>world viewable</i>.</p>

<p><a name="groups"></a><em><u>Can my student organization have a plans?</u></em><br />
Yes!  First, check to see if your organization has an active NT account.  If so, you can simply log in with that username and password.  If not, <a href="mailto:aceit@amherst.edu?subject=Account Request">contact IT</a> and see if they can set your organization up with one.</p>

<p><a name="shared"></a><em><u>Can I share my plan?</u></em><br />
Yes!  If you would like other people to be able to edit your plan (as in the case of a organization's plan), enable <em>sharing</em> on the preferences page.  Once that has been done, you can enter a list of people who will be allowed to change the plan.</p>

<p><a name="migration"></a><em><u>I'm an alumnus/a.  When do I need to start using my alumni account?</u></em><br />
IT typically allows graduates' NT accounts to work until the fall after graduation.  <em>However</em>, this is not always the case, and they may continue to work longer.  Therefore, you may continue using your NT account until it stops working or you may immediately switch to your alumni account when you receive it.  It's up to you.</p>

<p><a name="migration_how"></a><em><u>What happens to my old plan, archives, and planwatch when I start using my alumni account?</u></em><br />
If your alumni username is the same as your NT username, but with your (2-digit) graduation year appended, your settings and data should follow you.  In addition, you will automatically appear on your friends' planwatches with your new username.  If your alumni username differs (e.g., your last name was formerly truncated, as in the case of the author's), your settings and data will continue to be attached to your old username and you will have to start anew.  However, if you email <em><a href="mailto:planworld@note.amherst.edu">planworld@note.amherst.edu</a></em> with your new and old usernames when you switch, we may be able to help you transparently migrate, as well as preserve your data.</p>

<p><a name="snitch"></a><u><i>What is</i> <strong>snitch</strong> <i>
and how does it work?</i></u><br /> A little known function carried over
from VAX (developed by Jonathan Welch, '84), <i>snitch</i> allows you to view a list of users that have
viewed your plan (if those users also have <i>snitch</i> enabled), and
vice-versa.  However, disabling <i>snitch</i> clears all past entries;
thus you can't turn it on quickly and turn it off.</p>

<p><a name="snoop"></a><u><i>What is</i> <strong>snoop</strong> <i>and
how does it work?</i></u><br /> <i>Snoop</i> is the natural complement
to <i>snitch</i>.  Where <i>snitch</i> allows one to see who has been
reading their plan, <i>snoop</i> provides the means to see who has
been referencing yours.  The combination of the two allows for easier
conversing through plans (although this does not mean that plans
cannot and should not be used for anything else you may choose).</p>

<p><a name="send"></a><u><i>What is</i> <strong>send</strong> <i>and
how does it work?</i></u><br /> <i>Send</i> allows users to communicate with one another on a more personal level than <i>snoop</i> and more informally than email.</p>

<p><a name="themes"></a><u><i>Can I create my own planworld</i> <strong>theme</strong><i>?</i></u>
<br /> 

You can!  You need to create a style sheet that follows our rules
and submit it to your local planworld administrator or <a
href="mailto:planworld-themes@note.amherst.edu">planworld-themes@note.amherst.edu</a>.
Probably, the best way to come up with a theme is look at the style
sheets we've got by saving some planworld pages as plain HTML and
messing around with colors and fonts and stuff to make it look how you
want it to look.  Before you submit the theme you should read Baker
Franke's <a
href="http://note.amherst.edu/~befranke/themes/themesDoc.html">ThemesDoc.html</a> to make sure you have everything you
need.  All themes are subject to administrative approval (come on, we
can't just throw any old theme up there) but we encourage any and all
to submit suggested themes so that we can make planworld look
snazzy.</p>

<p><a name="colors"></a><i><u>How do I insert images, colors, etc. into my plan?</u></i><br />
We're not going to spell it out for you; that's all part of the fun...
but check out these pages for some info...<br />
<ul>
<li><a href="http://htmlprimer.com/">HTML Primer</a></li>
<li><a href="http://www.amherst.edu/~wwjarnag/">Web Design Resource Site</a></li>
</ul></p>

<p><a name="disappear"></a><i><u>Why do HTML tags keep disappearing
from my plan?</u></i><br />
We try to be as inclusive as we can with allowed tags, but it's likely
that we've missed some.  If you believe we have, please email the <a
href="mailto:planworld@note.amherst.edu">Planworld development
team</a>.  In cases such as JavaScript, we have chosen to disallow
certain tags as we feel that they accelerate entropy in the community.
If none of these appears to be the problem, check your plan for
matching tags and quotation marks.</p>

<p><a name="who"></a><em><u>Who's behind planworld?</u></em><br />
For ancient (pre-web) history, read the <a href="<?php echo PW_URL_INDEX; ?>?id=about">about</a> page. In more recent times, Alex Hochron began this incarnation in the fall of 2000.  Seth Fitzsimmons joined him that winter, and with the help of Peter Kupfer, planworld was released to the world.  Since then, Seth has become the primary developer with theme-related assistance from Baker Franke and Matt Gordon.</p>
