          <center><h1>Welcome to Plans</h1></center>
            Plans has a plan!  Check out [plans] for the great debate on what we
 should
 call ourselves!<br>
 <br>
 ----<br><br>
 <i>The future of plans</i>:<br><br>
 Plans now have an official email account.  Send all plan related
 questions, comments, requests, etc... to plans@grinnell.edu instead of
 heckr@grinnell.edu.<br><br>
 I am officially giving my program to three other students on campus who
 volunteered to take on the responsibility of running Plans.  They are
 Jonathan Emmons, Jonathan Kensler, and Jonathan Wellons.  They will be
 responsible for creating, deleting, and reseting accounts, as
 well as answering questions about the system.<br><br>
 Seniors will be glad to know that they WILL NOT lose their plans after
 graduation.  In order to keep the plan system to a managable size, plan
 accounts that have not been logged into in any 6 months period will be
 deleted.  So
 don't forget to log in sometimes so that you don't lose your account.  If
 you know that you will be unable to log into plans for an extended period
 of time, email plans@grinnell.edu and they will extend this grace period.<br><br>
 I don't think I have anything else to say.  I'm glad that people like my
 little program.  I hope that Grinnell continues to use it after my
 graduation.<br><br>
 Love Always,<br>
 Rachel<br><br><br>
 ***<br><br>
 As you've just read, Rachel is passing the plans system over to us, the three
 Jonathans. We'd really like to take this opportunity to thank Rachel for her work in
 establishing and maintaining this web version of plans. She may have written the
 original version in only a few hours, but she has spent much more time answering
 emails, maintaining the plans system, and upgrading the plans system. For this, we
 (and the entire campus) owe her much gratitude. We wish her (and all outgoing
 seniors) the very best. 
 <br><br>
 Enjoy this plans system that Rachel has given us, and have a
 great summer everyone.<br><br>
 Jonathan, Jonathan, and Jonathan