<span class="trailer">&copy; Copyright 2001-2004 <a href="http://note.amherst.edu/" class="trailer" target="_blank" title="NOTE">NOTE</a><br />
<a href="http://note.amherst.edu/" class="trailer" title="The New Athenian">The New Athenian</a> |
<a href="http://directory.amherst.edu/" class="trailer" title="Online Directory">Directory</a> |
<a href="https://exchange.amherst.edu/" class="trailer" title="Exchange">Exchange</a> |
<a href="http://note.amherst.edu/whatis/" class="trailer" title="What is NOTE?">What is NOTE?</a> |
<a href="mailto:<?php echo PW_EMAIL; ?>" class="trailer" title="Email the planworld folks!">Contact Us</a></span>
